- id: '1766965923790'
  alias: Adaptive Lighting Scheduler Hue
  description: ''
  use_blueprint:
    path: danielpetrovic/adaptive-lighting-scheduler.yaml
    input:
      brightness_helper: input_number.adaptive_brightness
      color_temp_helper: input_number.adaptive_color_temp
      auto_adjust_enabled: true
      target_lights:
        entity_id:
        - light.kitchen_light_strip
        - light.ceiling_lamp_3
        - light.bedroom_sconce_1
        - light.bedroom_sconce_2
        - light.ceiling_lamp_2
        - light.ceiling_lamp_4
        - light.ceiling_lamp_1
        - light.desk_strip_1
        - light.foyer_2
        - light.front_closet
        - light.foyer_1
        - light.desk_lamp
        - light.hallway
      brightness_use_sunrise: true
      brightness_use_sunset: true
- id: '1766967153950'
  alias: Adaptive Lighting Scheduler (Torchiers)
  description: ''
  use_blueprint:
    path: danielpetrovic/adaptive-lighting-scheduler.yaml
    input:
      brightness_helper: input_number.adaptive_brightness_torchier
      color_temp_helper: input_number.adaptive_color_temp_torchier
      target_lights:
        entity_id:
        - light.living_room_floor_lamp_1
        - light.living_room_floor_lamp_2
        - light.bedroom_floor_lamp_1
        - light.bedroom_floor_lamp_2
      auto_adjust_enabled: true
      brightness_use_sunrise: true
      brightness_use_sunset: true
- id: '1766985172320'
  alias: Adaptive Lighting Scheduler (v2) Hue
  description: ''
  use_blueprint:
    path: gitJake1980/adaptive-lighting-schedule-renewal.yaml
    input:
      brightness_helper: input_number.adaptive_brightness
      color_temp_helper: input_number.adaptive_color_temp
      enabled_helper: input_boolean.toggle_adaptive_lighting
      disable_scene: scene.red_light_district
      target_lights:
        entity_id:
        - light.kitchen_light_strip
        - light.ceiling_lamp_3
        - light.desk_strip_1
        - light.bedroom_sconce_1
        - light.ceiling_lamp_2
        - light.ceiling_lamp_4
        - light.foyer_2
        - light.front_closet
        - light.ceiling_lamp_1
        - light.foyer_1
        - light.desk_lamp
        - light.hallway
        - light.bedroom_sconce_2
        - light.bedroom
        - light.foyer
      auto_adjust_enabled: true
      night_color_temp: 2500
      min_color_temp: 3000
- id: '1766986204083'
  alias: Adaptive Lighting Scheduler (v2) torchier
  description: ''
  use_blueprint:
    path: gitJake1980/adaptive-lighting-schedule-renewal.yaml
    input:
      brightness_helper: input_number.adaptive_brightness_torchier
      color_temp_helper: input_number.adaptive_color_temp_torchier
      enabled_helper: input_boolean.toggle_adaptive_lighting
      disable_scene: scene.red_light_district
      auto_adjust_enabled: true
      target_lights:
        entity_id:
        - light.bedroom_floor_lamp_1
        - light.bedroom_floor_lamp_2
        - light.living_room_floor_lamp_1
        - light.living_room_floor_lamp_2
      night_color_temp: 2000
      min_color_temp: 2500
      max_color_temp: 3500
