- id: '1766965923790'
  alias: Adaptive Lighting Scheduler Hue
  description: ''
  use_blueprint:
    path: danielpetrovic/adaptive-lighting-scheduler.yaml
    input:
      brightness_helper: input_number.adaptive_brightness
      color_temp_helper: input_number.adaptive_color_temp
      auto_adjust_enabled: true
      target_lights:
        entity_id:
        - light.kitchen_light_strip
        - light.ceiling_lamp_3
        - light.bedroom_sconce_1
        - light.bedroom_sconce_2
        - light.ceiling_lamp_2
        - light.ceiling_lamp_4
        - light.ceiling_lamp_1
        - light.desk_strip_1
        - light.foyer_2
        - light.front_closet
        - light.foyer_1
        - light.desk_lamp
        - light.hallway
      brightness_use_sunrise: true
      brightness_use_sunset: true
- id: '1766967153950'
  alias: Adaptive Lighting Scheduler (Torchiers)
  description: ''
  use_blueprint:
    path: danielpetrovic/adaptive-lighting-scheduler.yaml
    input:
      brightness_helper: input_number.adaptive_brightness_torchier
      color_temp_helper: input_number.adaptive_color_temp_torchier
      target_lights:
        entity_id:
        - light.living_room_floor_lamp_1
        - light.living_room_floor_lamp_2
        - light.bedroom_floor_lamp_1
        - light.bedroom_floor_lamp_2
      auto_adjust_enabled: true
      brightness_use_sunrise: true
      brightness_use_sunset: true
