- id: '1767664459099'
  alias: Adaptive Lighting Scheduler (v2) (hue)
  description: ''
  use_blueprint:
    path: gitJake1980/adaptive-lighting-schedule-renewal.yaml
    input:
      brightness_helper: input_number.adaptive_brightness
      color_temp_helper: input_number.adaptive_color_temp
      enabled_helper: input_boolean.toggle_adaptive_lighting
      auto_adjust_enabled: true
      target_lights:
        entity_id:
        - light.ceiling_lamp_1
        - light.ceiling_lamp_2
        - light.ceiling_lamp_3
        - light.ceiling_lamp_4
        - light.desk_strip_1
        - light.desk_lamp
        - light.kitchen_light_strip
        - light.front_closet
        - light.bedroom_sconce_1
        - light.bedroom_sconce_2
        - light.foyer_1
        - light.foyer_2
        - light.gigabyte_geforce_rtx_4070_ti_gaming_oc
        - light.nzxt_smart_device_v2
        - light.z690_aorus_elite_ax_ddr4
        - light.hallway
- id: '1767664637876'
  alias: Adaptive Lighting Scheduler (v2)
  description: ''
  use_blueprint:
    path: gitJake1980/adaptive-lighting-schedule-renewal.yaml
    input:
      brightness_helper: input_number.adaptive_brightness_torchiere
      color_temp_helper: input_number.adaptive_color_temp_torchiere
      enabled_helper: input_boolean.toggle_adaptive_lighting
      target_lights:
        entity_id:
        - light.living_room_floor_lamp_1
        - light.living_room_floor_lamp_2
        - light.bedroom_floor_lamp_1
        - light.bedroom_floor_lamp_2
      auto_adjust_enabled: true
