- id: '1767000915656'
  alias: Adaptive Lighting Scheduler (v2) Hue
  description: ''
  use_blueprint:
    path: gitJake1980/adaptive-lighting-schedule-renewal.yaml
    input:
      brightness_helper: input_number.adaptive_brightness
      color_temp_helper: input_number.adaptive_color_temp
      enabled_helper: input_boolean.toggle_adaptive_lighting
      target_lights:
        entity_id:
        - light.bedroom_sconce_1
        - light.bedroom_sconce_2
        - light.ceiling_lamp_1
        - light.ceiling_lamp_2
        - light.ceiling_lamp_3
        - light.ceiling_lamp_4
        - light.kitchen_light_strip
        - light.foyer_1
        - light.foyer_2
        - light.desk_strip_1
        - light.desk_lamp
        - light.front_closet
        - light.hallway
        - light.openrgb
      auto_adjust_enabled: true
      night_brightness: 10
      night_color_temp: 2500
      min_color_temp: 3000
- id: '1767001075413'
  alias: Adaptive Lighting Scheduler (v2) torchier
  description: ''
  use_blueprint:
    path: gitJake1980/adaptive-lighting-schedule-renewal.yaml
    input:
      brightness_helper: input_number.adaptive_brightness_torchier
      color_temp_helper: input_number.adaptive_color_temp_torchier
      enabled_helper: input_boolean.toggle_adaptive_lighting
      target_lights:
        entity_id:
        - light.living_room_floor_lamp_1
        - light.living_room_floor_lamp_2
        - light.bedroom_floor_lamp_1
        - light.bedroom_floor_lamp_2
      auto_adjust_enabled: true
      night_brightness: 10
      night_color_temp: 2000
      min_color_temp: 2500
      max_color_temp: 3500
